### ISSUE TITLE
Add loader for Suomi24 korp api

### ISSUE THREAD

**Issue by juhopaak** [HIIT/hybra-core#14]
<a href="https://github.com/juhopaak"><img src="https://avatars1.githubusercontent.com/u/16080355?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [juhopaak](https://github.com/juhopaak)**
_Tue Jan 24 09:09:52 2017_
_Originally opened as https://github.com/HIIT/hybra-core-2/issues/14_

----

**Comment by matnel** [comment]
Korp API on huono. Ei käytetä tähän aikaa.

**Comment by juhopaak** [comment]
Ok, plugataanko S24 jotain muuta kautta, vai jätetäänkö hautumaan?
