### ISSUE TITLE
Add an example how to find the most common authors using counters.count_authors

### ISSUE THREAD

**Issue by juhopaak** [HIIT/hybra-core#22]
<a href="https://github.com/juhopaak"><img src="https://avatars1.githubusercontent.com/u/16080355?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [juhopaak](https://github.com/juhopaak)**
_Fri Feb 24 10:53:32 2017_
_Originally opened as https://github.com/HIIT/hybra-core-2/issues/22_

----

**Comment by matnel** [comment]
Done in counter.py?

**Comment by juhopaak** [comment]
counters.py method "counts_author" does return author counts, but does not specify most common authors. However, getting the most common ones from the returned Counter object is straightforward, so maybe we do not need a method for doing this anymore?

**Comment by matnel** [comment]
Maybe we should add an example of this to the documentation on using the Counter -object for this :)

**Comment by matnel** [comment]
@EeliH fixed this in commits e36b65aa579b8ac024fe71f0f4be2f6b630de5f2 and 064966d938fcd2cf3179214dfb695ad0b49f63e4 . Closing issue.
