### ISSUE TITLE
Modify all data to standard common format in loaders

### ISSUE THREAD

**Issue by matnel** [HIIT/hybra-core#3]
All the real keys from data are made explicit by adding an underscore before them, i.e. _title, _likes, etc. This indicates they should not be used in all data formats but carefully check if such data type truely exists.

Common data is
* creator
* source (i.e. Facebook, news_media, ...)
* source_detail (such as: page name, media outlate name, ...)
* text_content
* timestamp
* url

**Comment by juhopaak** [comment]
If there is a missing key in the data, should the loader add a Nonetype object or an empty strings as the common data value?

**Comment by matnel** [comment]
Should we flag these potentially broken values and return them in a separate list?

**Comment by juhopaak** [comment]
Do you mean that in the case of a missing key, the common data would not include that key, but the key would instead be appended to a separate list, and that each data loader would then return two lists: one with the data and one with all the keys to all broken common data values?

**Comment by matnel** [comment]
What I thought, is often I might run this like this:

for post in facebook():
   if 'cat' in post['text_content']:
         print "Has cats"

and this breaks if there is no text_content variable for some reason (e.g., it was only a photo posted). And that would be super sad and would be nice if we make sure these would not happen :D So, in this case, it would be nice if post['text_content'] would return an empty string AND some marker that the data was broken in this case and we managed that for you.
