### ISSUE TITLE
Fix crashing when making a Futusome query that is an url or contains umlauts

### ISSUE THREAD

**Issue by juhopaak** [HIIT/hybra-core#30]
<a href="https://github.com/aasitus"><img src="https://avatars3.githubusercontent.com/u/6010477?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aasitus](https://github.com/aasitus)**
_Fri Mar 31 11:04:13 2017_
_Originally opened as https://github.com/HIIT/hybra-core-2/issues/37_

----

**Comment by juhopaak** [comment]
<a href="https://github.com/juhopaak"><img src="https://avatars1.githubusercontent.com/u/16080355?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [juhopaak](https://github.com/juhopaak)**
_Wed Apr 12 11:12:19 2017_

----

Fixed issue with urls (fa5e969), but still to determine whether the issue remains for umlauts.

**Comment by matnel** [comment]
Can someone test this to see if we could close the issue?
