### ISSUE TITLE
Fix plot display methods not to return but to draw plots inline

### ISSUE THREAD

**Issue by juhopaak** [HIIT/hybra-core#32]
<a href="https://github.com/matnel"><img src="https://avatars2.githubusercontent.com/u/301760?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [matnel](https://github.com/matnel)**
_Tue Apr 11 19:08:39 2017_
_Originally opened as https://github.com/HIIT/hybra-core-2/issues/40_

----

Now:

```
import IPython
for i in range(0,13):
    print topics_of_interest[i]
    IPython.display.display_html( hybra.describe( topics[i] ) )
```

Should be

```
for i in range(0,13):
    print topics_of_interest[i]
   hybra.describe( topics[i] )
```

**Comment by matnel** [comment]
Related to #55
