### ISSUE TITLE
Fix d3.js initialization to work in any Jupyter notebook cell

### ISSUE THREAD

**Issue by ghost** [HIIT/hybra-core#55]
Trying to use hybra.describe(data_yle) it prints: 

"Entries together 6434
Number of different authors 1
First post 2007-06-28 21:44:31
Last post 2009-03-31 23:41:41
Data sources
- Yle Uutiset 6434
Javascript error adding output!
ReferenceError: d3 is not defined
See your browser Javascript console for more details."

or hybra.timeline( datasets=[data_yle], colors=['red'] )
"Javascript error adding output!
ReferenceError: d3 is not defined
See your browser Javascript console for more details."

but hybra.wordcloud(data_yle) works just fine.

**Comment by juhopaak** [comment]
Have you called the hybra.set_data_path() method before using describe? As of current, this method initializes d3.js, which is used for for timeline and network visualizations.

**Comment by ghost** [comment]
Yes. But I was calling set.data.path() and hybra.data() in same Jupyter cell. Tried calling them in separate  cells   just now and it seems to be working if your call them separately.

**Comment by juhopaak** [comment]
Ah ok, thanks for filing the issue. I'll modify this to concern d3.js initialization in notebook cells. We'll see if this could be made to work smoother with the notebook.
