### ISSUE TITLE
timeline: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by ghost** [HIIT/hybra-core#56]
I did a git pull yesterday for the latest modifications and ran into some new errors. 

Everything works just fine until hybra.timeline(). 
Hybra.describe works just fine and draws the timeline but when calling hybra.timeline( datasets=[data_yle], colors=['red']) I get an error saying: 

"ValueError                                Traceback (most recent call last)
<ipython-input-11-6fd43e2a6771> in <module>()
      1 #hybra.timeline( datasets=[data_yle], colors=['red'] )
----> 2 hybra.timeline( datasets=[data_yle], colors=['red']) #TäMÄ PITÄÄ RAPORTOIDA!!

/Users/tuomassoila/OneDrive - University of Helsinki/Maisteri/koodit/hybra/core/hybra.pyc in timeline(**kwargs)
     95     from IPython.core.display import display, HTML
     96 
---> 97     return display( HTML( module_timeline.create_timeline( **kwargs ) ) )
     98 
     99 def network( data ):

/Users/tuomassoila/OneDrive - University of Helsinki/Maisteri/koodit/hybra/core/timeline/module_timeline.pyc in create_timeline(datasets, colors)
     14     if not datasets: return "No data given to create timeline."
     15 
---> 16     plots = create_plots( datasets )
     17 
     18     graph_div_id = int( time.time() * 1000 )

/Users/tuomassoila/OneDrive - University of Helsinki/Maisteri/koodit/hybra/core/timeline/module_timeline.pyc in create_plots(datasets)
     35 
     36     for data in datasets:
---> 37         x_axis, y_axis = create_axes( data )
     38         plots.append( create_data_points( x_axis, y_axis ) )
     39 

/Users/tuomassoila/OneDrive - University of Helsinki/Maisteri/koodit/hybra/core/timeline/module_timeline.pyc in create_axes(data)
     47     y_axis = Counter( dates )
     48 
---> 49     start_date = min( y_axis )
     50     end_date = max( y_axis )
     51     delta = end_date - start_date"

By looking at Hybra module_timeline.py, I would guess that the problem comes from def create_axes function which does not check for empty values.

**Comment by juhopaak** [comment]
Thanks for this. I was able to reproduce the error and did a fix in f52c737. Let me know if this fixed the bug for you as well, so we can close this issue.

**Comment by ghost** [comment]
fast action :) Yes the issue has been fixed now! thanks!

**Comment by juhopaak** [comment]
Closing the issue due to f52c737.

**Comment by ghost** [comment]
Maybe I acted too hastily. It works only for the first time any of these commands  are called. 

If I run from beginning the imports and data_path commands it gives corrertly:

hybra.describe(data_yle) gives me: 
Entries together 6434
Number of different authors 1
First post 2007-06-28 21:44:31
Last post 2009-03-31 23:41:41
Data sources
- Yle Uutiset 6434
Data structure
{'_author': 'text',
 '_captions': ['text'],
 '_categories': ['text'],
 '_datetime_list': ['text'],
 '_domain': 'text',
 '_http': 'number',
 '_images': ['text'],
 '_ingress': 'text',
 '_text': 'text',
 '_title': 'text',
 '_url': 'text',
 'broken': {},
 'creator': 'text',
 'images': ['text'],
 'links': [],
 'links_domains': [],
 'source': 'text',
 'source_detail': 'text',
 'text_content': 'text',
 'timestamp': 'time',
 'url': 'text'}"

But after this, if I call  hybra.timeline( datasets=[data_yle], colors=['red']):
"Empty datasets in list!"

or

hybra.wordcloud(data_yle):
"Dataset empty."

And also if I run first the timeline command it works but after that the others give: "Dataset empty." or "Empty datasets in list!"

**Comment by juhopaak** [comment]
Yes, this is a feature resulting from the use of generators instead of lists in the data loaders. Generator objects are emptied after they have been iterated over, which all of those methods do. 

This means that when using the visualization methods repeatedly, you will have to either reload the data in between or else change the data to a list before making the repeated calls:

data_yle = list(data_yle)

Generators enable large datasets to be loaded without exhausting memory, but come with this trade-off. (see: http://intermediatepythonista.com/python-generators)

**Comment by ghost** [comment]
Okay. Thanks for the info!
